sudo:             false

language:         python

python:
  - 3.6.5

branches:
  - master

before_script:
  - cd src
  - python test_syntax.py

script:
  - python run-file.py "test.ros"
  - #python run-line.py "print_message.Hello World"
  - pasteurize -w syntax.py
  - mv $PWD/syntax.py $PWD/syntax2.py
  - pasteurize -w run-file.py
  - mv $PWD/run-file.py $PWD/run-file2.py

before_deploy:
  - cd ..
  - mkdocs build --verbose --clean --strict

deploy:
  provider:       pages
  skip_cleanup:   true
  github_token:   $github_token
  local_dir:      site
  on:
    branch:       master

after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
     -H "X-Auth-Email: ${email}" \
     -H "X-Auth-Key: ${cf_api_key}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${gh_repo}
  - mv -f ${files} ${repo}
  - cd ${repo}
  - git remote
  - git config user.email ${email}
  - git config user.name ${user}
  - git add ${files}
  - git commit -m "${MESSAGE}"
  - git push "https://${github_token}@${gh_repo}" master > /dev/null 2>&1

notifications:
  email:          false
