sudo:              false

addons:
  apt:
    packages:
      - openjdk-7-jre

language:          python

python:
  - 3.6.5

branches:
  - master

before_install:
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Code.git
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "Richienb"

install:
  - pip install -r requirements.txt
  - curl -L -o jython-installer.jar https://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar
  - java -jar jython-installer.jar --silent --directory runtime --type minimum --include mod
  - pip install -r requirements.txt --target "$PWD\runtime\Lib\site-packages"

before_script:
  - autopep8 -v -i -r -a -a -a $PWD/src
  - git add *
  - git diff-index --quiet HEAD || git commit -m "Normalised files to follow the PEP8 specification [skip ci]" && git push origin HEAD:master
  - cd src

script:
  - python test_syntax.py
  - pylint $PWD
  - flake8 --verbose $PWD
  - python run_file.py "test.ros"
  - #python run-line.py "print_message.Hello World"

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - mkdocs build --verbose --clean --strict

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master

after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
     -H "X-Auth-Email: ${email}" \
     -H "X-Auth-Key: ${cf_api_key}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

notifications:
  email:           false
