env:
  global:
    - GIT_NAME: "'Richienb'"
    - GIT_EMAIL: richiebendall@gmail.com
    - GH_REF: git@github.com:Richienb/ROS-Code.git

language: python

python:
  - 3.6.5

branches:
  - master

before_script:
  - pip install mkdocs mkdocs-material
  - pip install MarkdownHighlight

script:
  - cd src
  - python run-file.py "test.ros"
  - #python run-line.py "print_message.Hello World"
  - cd ..
  - openssl aes-256-cbc -K $encrypted_dac6f82e1309_key -iv $encrypted_dac6f82e1309_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval `ssh-agent -s`
  - ssh-add deploy-key
  - git config user.name "Richienb"
  - git config user.email "richiebendall@gmail.com"
  - git remote add gh-token "${GH_REF}";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token; git push gh-token gh-pages; fi;

notifications:
  email: false
