sudo:              false

language:          python

python:
  - 3.6.5

branches:
  - master

before_script:
  - cd src
  - python test_syntax.py

script:
  - python run-file.py "test.ros"
  - #python run-line.py "print_message.Hello World"

before_deploy:
  - cd ..
  - mkdocs build --verbose --clean --strict

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master

after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
     -H "X-Auth-Email: ${email}" \
     -H "X-Auth-Key: ${cf_api_key}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

notifications:
  email:           false
