sudo:              false

addons:
  apt:
    packages:
      - openjdk-8-jre
      - build-essential
      - build-dep
      - python2.7

cache:
  directories:
    - $TRAVIS_BUILD_DIR/python-source
    - $TRAVIS_BUILD_DIR/python-compiled

language:          python

python:
  - 3.6.5

branches:
  - master

before_install:
  - git remote set-url origin https://Richienb:${github_token}@github.com/Richienb/ROS-Code.git
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "Richienb"
  - find $TRAVIS_BUILD_DIR/ci -type f -iname "*.sh" -exec chmod +x {} \;

install:
  - pip install -r requirements.txt
  - $TRAVIS_BUILD_DIR/ci/install-python.sh

before_script:
  - cd src
  - BEFOREHASH=find /my/dir -mindepth 1 -type f -print0 | sort -z | sha1sum
  - $TRAVIS_BUILD_DIR/ci/autoop.sh
  - AFTERHASH=find /my/dir -mindepth 1 -type f -print0 | sort -z | sha1sum
  - $TRAVIS_BUILD_DIR/ci/verifycommit.sh

script:
  - python test_syntax.py
  - python run_file.py "test.ros"
  - #python run-line.py "print_message.Hello World"

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - mkdocs build --verbose --clean --strict

deploy:
  - provider:        pages
    skip_cleanup:    true
    github_token:    $github_token
    local_dir:       site
    on:
      branch:        master

after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
     -H "X-Auth-Email: ${email}" \
     -H "X-Auth-Key: ${cf_api_key}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

after_success:
  - pylint $PWD
  - flake8 --verbose $PWD

notifications:
  email:           false
