sudo:             false

language:         python

python:
  - 3.6.5

branches:
  - master

before_install:
  - git config --global user.email "richiebendall@gmail.com"
  - git config --global user.name "Richienb"
  
install:
  - pip install -r requirements.txt
  - git clone https://Richienb:${github_token}@github.com/Richienb/ROS-Code.git ./repo

before_script:
  - cd src
  - python test_syntax.py

script:
  - python run-file.py "test.ros"
  - #python run-line.py "print_message.Hello World"

before_deploy:
  - cd ..
  - mkdocs build --verbose --clean --strict

deploy:
  provider:       pages
  skip_cleanup:   true
  github_token:   $github_token
  local_dir:      site
  on:
    branch:       master

after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
     -H "X-Auth-Email: ${email}" \
     -H "X-Auth-Key: ${cf_api_key}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

after_success:
  - cd repo
  - pasteurize -w syntax.py
  - mv $PWD/syntax.py $PWD/syntax2.py
  - pasteurize -w run-file.py
  - mv $PWD/run-file.py $PWD/run-file2.py
  - git add syntax2.py run-file2.py
  - git commit -m "Added Python 2 Backwards Compatible Files [skip ci]"
  - git push

notifications:
  email:          false
