sudo:              false

language:          python

python:
  - 3.6.5

branches:
  - master

before_install:
  - sudo apt-get update

script:
  - cd src
  - python run-file.py "test.ros"
  - #python run-line.py "print_message.Hello World"
  - cd ..

before_deploy:
  - pip install mkdocs mkdocs-material pymdown-extensions Pygments
  - pip show mkdocs mkdocs-material pymdown-extensions Pygments
  - mkdocs build --verbose --clean --strict

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    $github_token
  local_dir:       site
  on:
    branch:        master

notifications:
  email:           false
