language: python

python:
  - 3.6.5

branches:
  - master

install:
- pip install mkdocs mkdocs-material

script:
  - cd src
  - python run-file.py "test.ros"
  - #python run-line.py "print_message.Hello World"
  - cd ..
  - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: master

notifications:
  email: false
