# Project Information
site_name:              ROS Code Documentation
site_description:       ROS Code is a revolutionary, modern and pleasing programming language to code in featuring a streamlined and speedy installation, a very straightforward and simplistic syntax and is provided as a Python 3 library.
site_author:            Richie Bendall
site_url:               https://ros-code.richie-bendall.ml

# Repository
repo_name:              Richienb/ROS-Code
repo_url:               https://github.com/Richienb/ROS-Code
edit_uri:               ""

# Copyright
copyright:              'Copyright &copy; 2017 - 2018 Richie Bendall'

# Configuration
theme:
  name:                 material
  palette:
    primary:            'indigo'
    accent:             'red'
  font:
    text:               'Roboto'
    code:               'Fira Code'
  language:             'en'
  favicon:              'assets/images/favicon.ico'
  logo:
    icon:               'code'

# Page Tree
nav:
    - Home:             index.md
    - Main:
      - Information Badges: badges.md
      - Commands: commands.md
    - Installation:
      - Install Modules: install-modules.md
      - Install From Source: install-source.md
    - Contribution:
      - Core Guidelines: guideline.md
      - Edit The Documentation: edit-docs.md
      - Edit The Source Code: edit-code.md
      - Future Plans:   plans.md
      - Packages Used:  packages.md
      - Release Guidelines: release-guidelines.md
      - Unit Testing:   unittesting.md
    - Other:
      - Recommended Syntax: syntax.md
      - Makefile Commands: makefile-commands.md
      - API Usage:      api-usage.md
    - Version 1:
      - Home:           versionone.md
      - Commands:       versionone-commands.md
      - Build Status:   versionone-buildstatus.md
      - Enable:         versionone-enable.md
      - Download And Install: versionone-install.md
      - Troubleshooting: versionone-troubleshooting.md
    - Fine Print:
      - Code Of Conduct: codeofconduct.md
      - Code License:   license.md
      - Documentation License: license-docs.md

# Customization
extra:
  social:
    - type:             globe
      link:             https://www.richie-bendall.ml
    - type:             github
      link:             https://github.com/Richienb
    - type:             user-circle
      link:             https://gravatar.com/richienb
    - type:             youtube
      link:             https://www.youtube.com/channel/UCxOiLzcbFeW-Ayz_MbgWIXw
    - type:             blogger
      link:             https://blog.richie-bendall.ml
    - type:             google-plus
      link:             https://plus.google.com/104023294057020158565
  disqus:               'ros-code'

extra_css:
  - 'https://cdn.rawgit.com/Richienb/0fc224502155f1f69973c473d5b5c90b/raw/ef234f31347da21d59bf05df308c7f46de7b2807/pymdown-details-polyfill.min.css'
  - 'https://unpkg.com/firacode@1.205.0/distr/fira_code.css'

extra_javascript:
  - 'https://cdn.rawgit.com/Richienb/0fc224502155f1f69973c473d5b5c90b/raw/1595668df391647b3db06c4179600a29c463870b/pymdown-details-polyfill.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - admonition
  - footnotes
  - meta
